{{- if and (eq .Values.global.mode "ACTIVE") (get (include "replicas" . | fromYaml) "autoscalingEnabled") }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "name-with-revision" ( dict "name" "istiod" "context" $) }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: istiod
    release: {{ .Release.Name }}
    istio.io/rev: {{ include "namespaced-revision" . }}
spec:
  maxReplicas: {{ get (include "replicas" . | fromYaml) "max" }}
  minReplicas: {{ get (include "replicas" . | fromYaml) "min" }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "name-with-revision" ( dict "name" "istiod" "context" $) }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: {{ get (include "replicas" . | fromYaml) "targetCPUUtilizationPercentage" }}
---
{{- end }}
