{{- if and (eq .Values.global.mode "ACTIVE") .Values.pilot.replicas.min .Values.pilot.replicas.max (gt (.Values.pilot.replicas.min | int) 0) (gt (.Values.pilot.replicas.max | int) (.Values.pilot.replicas.min | int)) }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "name-with-revision" ( dict "name" "istiod" "context" $) }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: istiod
    release: {{ .Release.Name }}
    istio.io/rev: {{ include "namespaced-revision" . }}
spec:
  maxReplicas: {{ .Values.pilot.replicas.max }}
  minReplicas: {{ .Values.pilot.replicas.min }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "name-with-revision" ( dict "name" "istiod" "context" $) }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: {{ .Values.pilot.replicas.targetCPUUtilizationPercentage }}
---
{{- end }}
