apiVersion: servicemesh.cisco.com/v1alpha1
kind: IstioControlPlane
metadata:
  name: icp-v115x
  namespace: istio-system
spec:
  version: 1.15.2
  mode: PASSIVE
  networkName: network2
  meshExpansion:
    enabled: true
