# The injection template to use for the gateway. If not set, no injection will be performed.
injectionTemplate: "gateway"

# Revision is set as 'version' label and part of the resource names when installing multiple control planes.
revision: "default"

type: ingress
runAsRoot: true

deployment:
  replicaCount: 1
  enablePrometheusMerge: true
  deploymentStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 25%
  metadata:
    labels: {}
    annotations: {}
  env: {}
  cpu:
    targetAverageUtilization: 80
  affinity: {}
  nodeSelector: {}
  priorityClassName: ""
  resources:
    limits:
      cpu: "2"
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 128Mi
  securityContext:
    runAsUser: 1337
    runAsGroup: 1337
    runAsNonRoot: true
  tolerations: []
  volumeMounts: []
  volumes: []
  podDisruptionBudget: {}
  podMetadata:
    labels: {}
    annotations: {}
  topologySpreadConstraints: []

service:
  type: ClusterIP
  metadata: {}
  ports: []
  selector: {}

externalService:
  addresses: {}

global:
  imagePullPolicy: "IfNotPresent"
  imagePullSecrets: []
