{{- if .Values.global.remotePilotAddress }}
apiVersion: v1
kind: Service
metadata:
  {{- if not .Values.global.externalIstiod }}
  # when local istiod is enabled, we can't use istiod service name to reach the remote control plane
  name: {{ include "name-with-revision" ( dict "name" "istiod-remote" "context" $) }}
  {{- else }}
  # when local istiod isn't enabled, we can use istiod service name to reach the remote control plane
  name: {{ include "name-with-revision" ( dict "name" "istiod" "context" $) }}
  {{- end }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 15012
    name: tcp-istiod
    protocol: TCP
  - port: 443
    targetPort: 15017
    name: tcp-webhook
    protocol: TCP
  {{- if not (regexMatch "^([0-9]*\\.){3}[0-9]*$" .Values.global.remotePilotAddress) }}
  # if the remotePilotAddress is not an IP addr, we use ExternalName
  type: ExternalName
  externalName: {{ .Values.global.remotePilotAddress }}
  {{- end }}
---
{{- end }}
